# Code generated by ChatGPT - any errors are property of OpenAI
# Define mailbox and date range
$Mailbox = "example@domain.com"
$StartDate = "01/01/2022"
$EndDate = "12/31/2022"

# Create an Outlook application object
$Outlook = New-Object -ComObject Outlook.Application

# Get the specified mailbox
$Namespace = $Outlook.GetNameSpace("MAPI")
$Folder = $Namespace.Folders | Where-Object { $_.EmailAddress -eq $Mailbox }

# Get the inbox and sent items folders by ID
$Inbox = $Folder.Folders.Item($Folder.DefaultStore.GetDefaultFolder(6).EntryID)
$SentItems = $Folder.Folders.Item($Folder.DefaultStore.GetDefaultFolder(5).EntryID)

# Get all emails in the specified date range in the inbox
$InboxEmails = $Inbox.Items.Restrict("[ReceivedTime] >= '$StartDate' AND [ReceivedTime] <= '$EndDate'")
$InboxEmailsPerMonth = $InboxEmails | Group-Object { $_.ReceivedTime.ToString("yyyy-MM") } | Select-Object Name, Count, @{Name="Size";Expression={($_.Group | Measure-Object Size -Sum).Sum / 1KB}}

# Get all emails in the specified date range in sent items
$SentEmails = $SentItems.Items.Restrict("[SentOn] >= '$StartDate' AND [SentOn] <= '$EndDate'")
$SentEmailsPerMonth = $SentEmails | Group-Object { $_.SentOn.ToString("yyyy-MM") } | Select-Object Name, Count, @{Name="Size";Expression={($_.Group | Measure-Object Size -Sum).Sum / 1KB}}

# Output the results
Write-Host "Inbox emails per month:"
$InboxEmailsPerMonth | Sort-Object Name | Format-Table -AutoSize

Write-Host "Sent emails per month:"
$SentEmailsPerMonth | Sort-Object Name | Format-Table -AutoSize

Write-Host "Total emails per month:"
$TotalEmailsPerMonth = $InboxEmailsPerMonth | ForEach-Object {
    $Name = $_.Name
    $Count = $_.Count + ($SentEmailsPerMonth | Where-Object { $_.Name -eq $Name }).Count
    $Size = $_.Size + ($SentEmailsPerMonth | Where-Object { $_.Name -eq $Name }).Size
    [PSCustomObject]@{ Name = $Name; Count = $Count; Size = $Size }
}
$TotalEmailsPerMonth | Sort-Object Name | Format-Table -AutoSize
